DROP TABLE UNIVERSITY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE AUTHORITIES CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE UNI_BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT_REASON CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE REPLY_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE USER_POINT CASCADE CONSTRAINTS;
DROP TABLE SEMESTER_CLASS CASCADE CONSTRAINTS;
DROP TABLE CLASS CASCADE CONSTRAINTS;
DROP TABLE CLASS_ASSESSMENT CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE CHAT_JOIN CASCADE CONSTRAINTS;
DROP TABLE FILES CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MNO;

/* 시퀀스 생성 */
CREATE SEQUENCE SEQ_MNO NOCACHE;



/* 대학관련 테이블 */
CREATE TABLE UNIVERSITY (
    UNI_NO   NUMBER       PRIMARY KEY,
    UNI_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE DEPARTMENT (
    DEPT_NO   NUMBER       PRIMARY KEY,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY,
    DEPT_NAME VARCHAR2(30) NOT NULL,
    UNIQUE(UNI_NO, DEPT_NAME)
);

/* 회원 및 권한 테이블 */
CREATE TABLE MEMBER (
    MEM_NO      NUMBER       PRIMARY KEY,
    MEM_ID      VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PW      VARCHAR2(100) NOT NULL,
    MEM_NAME    VARCHAR2(20) NOT NULL,
    DEPT_NO     NUMBER       REFERENCES DEPARTMENT NOT NULL,
    PHONE       VARCHAR2(13) NOT NULL,
    EMAIL       VARCHAR2(50) NOT NULL UNIQUE,
    CREATE_DATE DATE         DEFAULT SYSDATE,
    STATUS      CHAR(1)      DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE AUTHORITIES (
    AUTHORITY VARCHAR2(20),
    MEM_NO    NUMBER       REFERENCES MEMBER,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY,
    PRIMARY KEY(AUTHORITY, MEM_NO, UNI_NO)
);

/* 공지사항 테이블 */
CREATE TABLE NOTICE (
    NOTICE_NO      NUMBER        PRIMARY KEY,
    UNI_NO         NUMBER        REFERENCES UNIVERSITY,
    NOTICE_TITLE   VARCHAR2(50)  NOT NULL,
    NOTICE_CONTENT VARCHAR2(300),
    CREATE_DATE    DATE          DEFAULT SYSDATE,
    STATUS         CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

/* 게시판 관련 테이블 */
CREATE TABLE BOARD_TYPE (
    BTYPE_NO   NUMBER PRIMARY KEY,
    BTYPE_NAME VARCHAR2(20)
);
CREATE TABLE UNI_BOARD_TYPE (
    UNI_NO   NUMBER REFERENCES UNIVERSITY PRIMARY KEY,
    BTYPE_NO NUMBER REFERENCES BOARD_TYPE
);
CREATE TABLE BOARD (
    BOARD_NO      NUMBER        PRIMARY KEY,
    UBTYPE_NO     NUMBER        DEFAULT 0 REFERENCES UNI_BOARD_TYPE,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(300),
    BOARD_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    VIEW_COUNT    NUMBER        DEFAULT 0,
    CREATE_DATE   DATE          DEFAULT SYSDATE,
    STATUS        CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE BOARD_LIKE(
    BOARD_NO NUMBER REFERENCES BOARD,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(BOARD_NO, MEM_NO)
);
CREATE TABLE REPLY(
    REPLY_NO      NUMBER       PRIMARY KEY,
    BOARD_NO      NUMBER       REFERENCES BOARD NOT NULL,
    REPLY_CONTENT VARCHAR(200) NOT NULL,
    REPLY_WRITER  NUMBER       REFERENCES MEMBER NOT NULL,
    CREATE_DATE   DATE         DEFAULT SYSDATE,
    STATUS        CHAR(1)      DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE REPLY_LIKE(
    REPLY_NO NUMBER REFERENCES REPLY,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(REPLY_NO, MEM_NO)
);

/* 신고 테이블 */
CREATE TABLE REPORT_REASON(
    REASON_NO   NUMBER       PRIMARY KEY,
    REASON_NAME VARCHAR2(40)
);
CREATE TABLE REPORT(
    REPORT_NO      NUMBER        PRIMARY KEY,
    REPORT_MEM     NUMBER        REFERENCES MEMBER NOT NULL,
    REASON_NO      NUMBER        DEFAULT 0 REFERENCES REPORT_REASON,
    REASON_CONTENT VARCHAR2(100),
    TARGET_TYPE    VARCHAR2(20)  NOT NULL,
    TARGET_NO      NUMBER        NOT NULL,
    UNIQUE(REPORT_MEM, TARGET_TYPE, TARGET_NO)
);

/* 출석체크 및 포인트 */
CREATE TABLE ATTENDANCE(
    MEM_NO     NUMBER REFERENCES MEMBER,
    ATTEND_DAYS NUMBER DEFAULT 0,
    PRIMARY KEY(MEM_NO)
);
CREATE TABLE USER_POINT(
    MEM_NO NUMBER REFERENCES MEMBER,
    POINT   NUMBER DEFAULT 0,
    PRIMARY KEY(MEM_NO)
);

/* 강의 정보 */
CREATE TABLE CLASS(
    CLASS_NO       NUMBER       PRIMARY KEY,
    DEPT_NO        NUMBER       REFERENCES DEPARTMENT NOT NULL,
    CLASS_NAME     VARCHAR2(20) NOT NULL,
    PROFESSOR_NAME VARCHAR2(20) NOT NULL,
    UNIQUE(CLASS_NAME, PROFESSOR_NAME)
);
CREATE TABLE SEMESTER_CLASS(
    CLASS_NO   NUMBER       REFERENCES CLASS,
    DAYS       DATE         NOT NULL,
    START_TIME DATE         NOT NULL,
    END_TIME   DATE         NOT NULL,
    CLASS_ROOM VARCHAR2(20) NOT NULL,
    PRIMARY KEY(CLASS_NO)
);

/* 강의 평가 */
CREATE TABLE CLASS_ASSESSMENT(
    ASSE_NO     NUMBER PRIMARY KEY,
    MEM_NO      NUMBER REFERENCES MEMBER NOT NULL,
    CLASS_NO    NUMBER REFERENCES CLASS NOT NULL,
    HOMEWORK    NUMBER DEFAULT 1,
    GRADE       NUMBER DEFAULT 1, 
    TOTAL_SOCRE NUMBER DEFAULT 5
);

/* 시간표 */
CREATE TABLE SCHEDULE(
    SCHEDULE_NO NUMBER PRIMARY KEY,
    MEM_NO      NUMBER REFERENCES MEMBER NOT NULL,
    CLASS_NO    NUMBER REFERENCES SEMESTER_CLASS NOT NULL
);

/* 친구 */
CREATE TABLE FRIENDS(
    SENDER_NO   NUMBER  REFERENCES MEMBER,
    RECEIVER_NO NUMBER  REFERENCES MEMBER,
    STATUS      CHAR(1) DEFAULT 'N' CHECK (STATUS IN ('Y', 'N')),
    PRIMARY KEY(SENDER_NO, RECEIVER_NO)
);

/* 채팅 */
CREATE TABLE CHAT(
    CHAT_NO NUMBER PRIMARY KEY,
    CHAT_TITLE VARCHAR2(30) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
CREATE TABLE CHAT_MESSAGE(
    MSG_NO       NUMBER        PRIMARY KEY,
    CHAT_NO      NUMBER        REFERENCES CHAT NOT NULL,
    CHAT_MESSAGE VARCHAR2(100) NOT NULL,
    CHAT_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    CREATE_DATE  DATE          DEFAULT SYSDATE
);
CREATE TABLE CHAT_JOIN(
    MEM_NO  NUMBER REFERENCES MEMBER,
    CHAT_NO NUMBER REFERENCES CHAT,
    PRIMARY KEY(MEM_NO, CHAT_NO)
);

/* 첨부파일 */
CREATE TABLE FILES(
    FILE_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(20),
    CHANGE_NAME VARCHAR2(20),
    TARGET_TYPE VARCHAR2(20) NOT NULL,
    TARGET_NO   NUMBER NOT NULL
);

-----------------------------------------------------------------------

SELECT * FROM member;

INSERT INTO university VALUES(0, 'ROOT');
SELECT * FROM university;

INSERT INTO department VALUES(0, 0, 'ROOT');
select * from department;

commit;