DROP TABLE UNIVERSITY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE AUTHORITIES CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE UNI_BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT_REASON CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE REPLY_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE USER_POINT CASCADE CONSTRAINTS;
DROP TABLE SEMESTER_LECTURE CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE LECTURE_ASSESSMENT CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE CHAT_JOIN CASCADE CONSTRAINTS;
DROP TABLE FILES CASCADE CONSTRAINTS;
DROP TABLE persistent_logins CONSTRAINTS;

DROP SEQUENCE SEQ_MEM;
DROP SEQUENCE SEQ_UNI;
DROP SEQUENCE SEQ_DEPT;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_BTYPE;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_REASON;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_LECTURE;
DROP SEQUENCE SEQ_ASSE;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_CHAT;
DROP SEQUENCE SEQ_MSG;
DROP SEQUENCE SEQ_FILE;


/*========== SEQUENCE 생성 ==========*/

/* MEMBER 시퀀스 */
CREATE SEQUENCE SEQ_MEM NOCACHE;

/* 대학 시퀀스 */
CREATE SEQUENCE SEQ_UNI NOCACHE;

/* 학과 시퀀스 */
CREATE SEQUENCE SEQ_DEPT NOCACHE;

/* 공지사항 시퀀스 */
CREATE SEQUENCE SEQ_NOTICE NOCACHE;

/* 게시판 관련 시퀀스 */
CREATE SEQUENCE SEQ_BTYPE NOCACHE;
CREATE SEQUENCE SEQ_BOARD NOCACHE;
CREATE SEQUENCE SEQ_UBTYPE NOCACHE;
/* 댓글 시퀀스 */
CREATE SEQUENCE SEQ_REPLY NOCACHE;

/* 신고 관련 시퀀스 */
CREATE SEQUENCE SEQ_REASON NOCACHE;
CREATE SEQUENCE SEQ_REPORT NOCACHE;

/* 강의 관련 시퀀스 */
CREATE SEQUENCE SEQ_LECTURE NOCACHE;
CREATE SEQUENCE SEQ_ASSE NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE NOCACHE;

/* 채팅 관련 시퀀스 */
CREATE SEQUENCE SEQ_CHAT NOCACHE;
CREATE SEQUENCE SEQ_MSG NOCACHE;

/* 첨부파일 시퀀스 */
CREATE SEQUENCE SEQ_FILE NOCACHE;

--------------------------------------------------------------------------------

/*========== TABEL 생성 ==========*/

/* 대학관련 테이블 */
CREATE TABLE UNIVERSITY (
    UNI_NO   NUMBER       PRIMARY KEY,
    UNI_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE DEPARTMENT (
    DEPT_NO   NUMBER       PRIMARY KEY,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY NOT NULL,
    DEPT_NAME VARCHAR2(30) NOT NULL,
    UNIQUE(UNI_NO, DEPT_NAME)
);

/* 회원 및 권한 테이블 */
CREATE TABLE MEMBER (
    MEM_NO      NUMBER        PRIMARY KEY,
    MEM_ID      VARCHAR2(20)  NOT NULL UNIQUE,
    MEM_PW      VARCHAR2(100) NOT NULL,
    STUDENT_NO  NUMBER,
    MEM_NAME    VARCHAR2(20)  NOT NULL,
    DEPT_NO     NUMBER        REFERENCES DEPARTMENT NOT NULL,
    PHONE       VARCHAR2(13),
    CREATE_DATE DATE          DEFAULT SYSDATE,
    STATUS      CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE AUTHORITIES (
    AUTHORITY VARCHAR2(20),
    MEM_NO    NUMBER       REFERENCES MEMBER,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY,
    PRIMARY KEY(AUTHORITY, MEM_NO, UNI_NO)
);

/* 공지사항 테이블 */
CREATE TABLE NOTICE (
    NOTICE_NO      NUMBER        PRIMARY KEY,
    UNI_NO         NUMBER        REFERENCES UNIVERSITY,
    NOTICE_TITLE   VARCHAR2(50)  NOT NULL,
    NOTICE_CONTENT VARCHAR2(300),
    CREATE_DATE    DATE          DEFAULT SYSDATE,
    STATUS         CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

/* 게시판 관련 테이블 */
CREATE TABLE BOARD_TYPE (
    BTYPE_NO   NUMBER PRIMARY KEY,
    BTYPE_NAME VARCHAR2(20)
);
CREATE TABLE UNI_BOARD_TYPE (
    UBTYPE_NO NUMBER PRIMARY KEY,
    UNI_NO   NUMBER REFERENCES UNIVERSITY,
    BTYPE_NO NUMBER REFERENCES BOARD_TYPE,
    UNIQUE(UNI_NO, BTYPE_NO)
);
CREATE TABLE BOARD (
    BOARD_NO      NUMBER        PRIMARY KEY,
    UBTYPE_NO     NUMBER        DEFAULT 0 REFERENCES UNI_BOARD_TYPE,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(300),
    BOARD_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    VIEW_COUNT    NUMBER        DEFAULT 0,
    CREATE_DATE   DATE          DEFAULT SYSDATE,
    STATUS        CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE BOARD_LIKE(
    BOARD_NO NUMBER REFERENCES BOARD,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(BOARD_NO, MEM_NO)
);
CREATE TABLE REPLY(
    REPLY_NO      NUMBER       PRIMARY KEY,
    BOARD_NO      NUMBER       REFERENCES BOARD NOT NULL,
    REPLY_CONTENT VARCHAR(200) NOT NULL,
    REPLY_WRITER  NUMBER       REFERENCES MEMBER NOT NULL,
    CREATE_DATE   DATE         DEFAULT SYSDATE,
    STATUS        CHAR(1)      DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE REPLY_LIKE(
    REPLY_NO NUMBER REFERENCES REPLY,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(REPLY_NO, MEM_NO)
);

/* 신고 테이블 */
CREATE TABLE REPORT_REASON(
    REASON_NO   NUMBER       PRIMARY KEY,
    REASON_NAME VARCHAR2(40)
);
CREATE TABLE REPORT(
    REPORT_NO      NUMBER        PRIMARY KEY,
    REPORT_MEM     NUMBER        REFERENCES MEMBER NOT NULL,
    REASON_NO      NUMBER        DEFAULT 0 REFERENCES REPORT_REASON,
    REASON_CONTENT VARCHAR2(100),
    TARGET_TYPE    VARCHAR2(20)  NOT NULL,
    TARGET_NO      NUMBER        NOT NULL,
    UNIQUE(REPORT_MEM, TARGET_TYPE, TARGET_NO)
);

/* 출석체크 및 포인트 */
CREATE TABLE ATTENDANCE(
    MEM_NO      NUMBER REFERENCES MEMBER,
    ATTEND_DAYS DATE,
    COUNT       NUMBER DEFAULT 0,  
    PRIMARY KEY(MEM_NO)
);
CREATE TABLE USER_POINT(
    MEM_NO  NUMBER REFERENCES MEMBER,
    POINT   NUMBER DEFAULT 0,
    PRIMARY KEY(MEM_NO)
);

/* 강의 정보 */
CREATE TABLE LECTURE(
    LECTURE_NO     NUMBER       PRIMARY KEY,
    DEPT_NO        NUMBER       REFERENCES DEPARTMENT NOT NULL,
    LECTURE_NAME   VARCHAR2(20) NOT NULL,
    PROFESSOR_NAME VARCHAR2(20) NOT NULL,
    UNIQUE(LECTURE_NAME, PROFESSOR_NAME)
);
CREATE TABLE SEMESTER_LECTURE(
    LECTURE_NO   NUMBER       REFERENCES LECTURE,
    DAYS         DATE         NOT NULL,
    START_TIME   DATE         NOT NULL,
    END_TIME     DATE         NOT NULL,
    LECTURE_ROOM VARCHAR2(20) NOT NULL,
    PRIMARY KEY(LECTURE_NO)
);

/* 강의 평가 */
CREATE TABLE LECTURE_ASSESSMENT(
    ASSE_NO     NUMBER PRIMARY KEY,
    MEM_NO      NUMBER REFERENCES MEMBER NOT NULL,
    LECTURE_NO  NUMBER REFERENCES LECTURE NOT NULL,
    HOMEWORK    NUMBER DEFAULT 1,
    GRADE       NUMBER DEFAULT 1, 
    TOTAL_SCORE NUMBER DEFAULT 5
);

/* 시간표 */
CREATE TABLE SCHEDULE(
    SCHEDULE_NO NUMBER PRIMARY KEY,
    MEM_NO      NUMBER REFERENCES MEMBER NOT NULL,
    LECTURE_NO  NUMBER REFERENCES SEMESTER_LECTURE NOT NULL
);

/* 친구 */
CREATE TABLE FRIENDS(
    SENDER_NO   NUMBER  REFERENCES MEMBER,
    RECEIVER_NO NUMBER  REFERENCES MEMBER,
    STATUS      CHAR(1) DEFAULT 'N' CHECK (STATUS IN ('Y', 'N')),
    PRIMARY KEY(SENDER_NO, RECEIVER_NO)
);

/* 채팅 */
CREATE TABLE CHAT(
    CHAT_NO NUMBER PRIMARY KEY,
    CHAT_TITLE VARCHAR2(30) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
CREATE TABLE CHAT_MESSAGE(
    MSG_NO       NUMBER        PRIMARY KEY,
    CHAT_NO      NUMBER        REFERENCES CHAT NOT NULL,
    CHAT_MESSAGE VARCHAR2(100) NOT NULL,
    CHAT_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    CREATE_DATE  DATE          DEFAULT SYSDATE
);
CREATE TABLE CHAT_JOIN(
    MEM_NO  NUMBER REFERENCES MEMBER,
    CHAT_NO NUMBER REFERENCES CHAT,
    PRIMARY KEY(MEM_NO, CHAT_NO)
);

/* 첨부파일 */
CREATE TABLE FILES(
    FILE_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(225),
    CHANGE_NAME VARCHAR2(225),
    TARGET_TYPE VARCHAR2(20) NOT NULL,
    TARGET_NO   NUMBER NOT NULL
);

/* 로그인 유지(remember-me) */
CREATE TABLE persistent_logins (
  username        VARCHAR(64)  NOT NULL,
  series          VARCHAR(64)  PRIMARY KEY,
  token           VARCHAR(64)  NOT NULL,
  last_used       TIMESTAMP    NOT NULL
);

--------------------------------------------------------------------------------

DELETE university;
DELETE department;
DELETE member;
DELETE authorities;

SELECT * FROM UNIVERSITY;
SELECT * FROM DEPARTMENT;
SELECT * FROM MEMBER;
SELECT * FROM AUTHORITIES;

/* 마스터 정보 */
INSERT INTO UNIVERSITY VALUES(0, 'MASTER');
INSERT INTO DEPARTMENT VALUES(0, 0, 'MASTER');
-- INSERT INTO MEMBER VALUES(0, 'master', 'master00', NULL, 'master', 0, NULL, DEFAULT, DEFAULT);
INSERT INTO AUTHORITIES VALUES('ROLE_USER', 0, 0);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 0, 0);
INSERT INTO AUTHORITIES VALUES('ROLE_MASTER', 0, 0);

/* 서울대 정보 */
INSERT INTO UNIVERSITY VALUES(SEQ_UNI.NEXTVAL, '서울대학교');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '공통교양');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건설환경도시공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건설환경도시공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '기계공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '재료공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '전기정보공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '컴퓨터공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '화학생물공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건축학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '산업공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '에너지자원공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '원자핵공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '조선해양공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '항공우주공학과');
-- INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'seoul', 'seoul000', NULL, 'seoul', 1, NULL, DEFAULT, DEFAULT);
INSERT INTO AUTHORITIES VALUES('ROLE_USER', 1, 1);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 1, 1);

/* 연세대 정보 */
INSERT INTO UNIVERSITY VALUES(SEQ_UNI.NEXTVAL, '연세대학교');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '공통교양');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '화공생명공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '전기전자공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '기계공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '사회환경시스템공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '건축공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '신소재공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '도시공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '산업공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '시스템반도체공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '디스플레이융합공학과');
-- INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'yonsei', 'yonsei00', NULL, 'yonsei', 15, NULL, DEFAULT, DEFAULT);
INSERT INTO AUTHORITIES VALUES('ROLE_USER', 2, 2);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 2, 2);


commit;

