/* =========================================================
   발표용 최종 더미데이터
   실행 순서:
   1) 기존 테이블 생성 + 기본 데이터 SQL 실행
   2) 아래 최종 더미 SQL 실행

   반영 조건:
   - 공통교양은 관리자만 사용
   - 일반회원은 공통교양 배정 금지
   - 일부 회원은 가입 승인 대기용으로 ROLE_USER 미부여
   - 신고 데이터 강화
   ========================================================= */


/* =========================================================
   1. 고려대학교 추가
   ========================================================= */

INSERT INTO UNIVERSITY
VALUES (SEQ_UNI.NEXTVAL, '고려대학교', DEFAULT);


/* =========================================================
   2. 고려대학교 학과 추가
   ========================================================= */

INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '공통교양' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '컴퓨터학과' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '전기전자공학부' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '기계공학부' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '화공생명공학과' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '산업경영공학부' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '건축사회환경공학부' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '신소재공학부' FROM DUAL;
INSERT INTO DEPARTMENT
SELECT SEQ_DEPT.NEXTVAL, (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'), '생명과학부' FROM DUAL;


/* =========================================================
   3. 고려대학교 관리자 추가
   - 공통교양은 관리자만 허용
   ========================================================= */

INSERT INTO MEMBER
SELECT SEQ_MEM.NEXTVAL,
       'korea',
       '$2a$10$8L4WDdUeAu4QdMOp.sB12OlsGUiMgY6aIvyRA6uoY23p8E4Bph7km',
       NULL,
       'korea',
       (SELECT DEPT_NO
          FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '공통교양'),
       NULL,
       SYSDATE,
       'Y'
FROM DUAL;

INSERT INTO AUTHORITIES
SELECT 'ROLE_USER',
       MEM_NO,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
FROM MEMBER
WHERE MEM_ID = 'korea';

INSERT INTO AUTHORITIES
SELECT 'ROLE_ADMIN',
       MEM_NO,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
FROM MEMBER
WHERE MEM_ID = 'korea';


/* =========================================================
   4. 고려대학교 게시판 연결
   ========================================================= */

INSERT INTO BOARD_TYPE
VALUES (SEQ_BTYPE.NEXTVAL, '고대광장');

INSERT INTO UNI_BOARD_TYPE
SELECT SEQ_UBTYPE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       (SELECT BTYPE_NO FROM BOARD_TYPE WHERE BTYPE_NAME = '자유게시판')
FROM DUAL;

INSERT INTO UNI_BOARD_TYPE
SELECT SEQ_UBTYPE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       (SELECT BTYPE_NO FROM BOARD_TYPE WHERE BTYPE_NAME = '질문답변')
FROM DUAL;

INSERT INTO UNI_BOARD_TYPE
SELECT SEQ_UBTYPE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       (SELECT BTYPE_NO FROM BOARD_TYPE WHERE BTYPE_NAME = '사건사고')
FROM DUAL;

INSERT INTO UNI_BOARD_TYPE
SELECT SEQ_UBTYPE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       (SELECT BTYPE_NO FROM BOARD_TYPE WHERE BTYPE_NAME = '고대광장')
FROM DUAL;


/* =========================================================
   5. 고려대학교 강의 추가
   ========================================================= */

INSERT INTO LECTURE
SELECT SEQ_LECTURE.NEXTVAL,
       (SELECT DEPT_NO FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '공통교양'),
       '대학영어',
       '박교수'
FROM DUAL;

INSERT INTO LECTURE
SELECT SEQ_LECTURE.NEXTVAL,
       (SELECT DEPT_NO FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '컴퓨터학과'),
       '자료구조',
       '이교수'
FROM DUAL;

INSERT INTO LECTURE
SELECT SEQ_LECTURE.NEXTVAL,
       (SELECT DEPT_NO FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '컴퓨터학과'),
       '운영체제',
       '최교수'
FROM DUAL;

INSERT INTO LECTURE
SELECT SEQ_LECTURE.NEXTVAL,
       (SELECT DEPT_NO FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '전기전자공학부'),
       '회로이론',
       '정교수'
FROM DUAL;

INSERT INTO LECTURE
SELECT SEQ_LECTURE.NEXTVAL,
       (SELECT DEPT_NO FROM DEPARTMENT
         WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
           AND DEPT_NAME = '기계공학부'),
       '열역학',
       '한교수'
FROM DUAL;


/* =========================================================
   6. 일반회원 추가
   - 공통교양 배정 금지
   ========================================================= */

-- 서울대
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600102', '박서준', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '컴퓨터공학부'), '010-1000-1002', SYSDATE - 12, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user03', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600103', '최유진', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '전기정보공학부'), '010-1000-1003', SYSDATE - 10, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user04', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600104', '한지민', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '기계공학부'), '010-1000-1004', SYSDATE - 8, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user05', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600105', '오민석', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '건축학과'), '010-1000-1005', SYSDATE - 15, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user06', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600106', '강수진', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '산업공학과'), '010-1000-1006', SYSDATE - 14, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user07', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600107', '윤태호', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '화학생물공학부'), '010-1000-1007', SYSDATE - 13, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user08', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600108', '서예지', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '재료공학부'), '010-1000-1008', SYSDATE - 12, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user09', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600109', '정다은', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '에너지자원공학과'), '010-1000-1009', SYSDATE - 11, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user10', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600110', '임준혁', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '항공우주공학과'), '010-1000-1010', SYSDATE - 10, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user11', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600111', '배지훈', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '조선해양공학과'), '010-1000-1011', SYSDATE - 9, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user12', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600112', '노가은', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '원자핵공학과'), '010-1000-1012', SYSDATE - 8, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user13', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600115', '문서연', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '건설환경도시공학부'), '010-1000-1015', SYSDATE - 6, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user14', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600116', '차민우', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '컴퓨터공학부'), '010-1000-1016', SYSDATE - 5, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_user15', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600117', '백수아', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '전기정보공학부'), '010-1000-1017', SYSDATE - 4, 'Y' FROM DUAL;

-- 연세대
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600202', '김도현', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '전기전자공학부'), '010-2000-2002', SYSDATE - 11, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user03', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600203', '이수빈', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '건축공학과'), '010-2000-2003', SYSDATE - 9, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user04', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600204', '정예린', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '산업공학과'), '010-2000-2004', SYSDATE - 7, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user05', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600205', '최민재', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '기계공학부'), '010-2000-2005', SYSDATE - 15, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user06', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600206', '한소희', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '신소재공학부'), '010-2000-2006', SYSDATE - 14, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user07', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600207', '문지후', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '도시공학과'), '010-2000-2007', SYSDATE - 13, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user08', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600208', '송하린', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '사회환경시스템공학부'), '010-2000-2008', SYSDATE - 12, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user09', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600209', '조현우', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '시스템반도체공학과'), '010-2000-2009', SYSDATE - 11, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user10', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600210', '유채린', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '디스플레이융합공학과'), '010-2000-2010', SYSDATE - 10, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user11', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600211', '박시우', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '화공생명공학부'), '010-2000-2011', SYSDATE - 9, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user12', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600212', '김나현', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '기계공학부'), '010-2000-2012', SYSDATE - 8, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user13', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600215', '양도현', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '화공생명공학부'), '010-2000-2015', SYSDATE - 6, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user14', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600216', '고은채', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '전기전자공학부'), '010-2000-2016', SYSDATE - 5, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_user15', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600217', '서지후', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '기계공학부'), '010-2000-2017', SYSDATE - 4, 'Y' FROM DUAL;

-- 고려대
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600301', '김도윤', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '컴퓨터학과'), '010-3000-3001', SYSDATE - 12, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600302', '박하은', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '전기전자공학부'), '010-3000-3002', SYSDATE - 11, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user03', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600303', '이서준', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '기계공학부'), '010-3000-3003', SYSDATE - 10, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user04', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600304', '최지안', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '화공생명공학과'), '010-3000-3004', SYSDATE - 9, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user05', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600305', '정유빈', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '산업경영공학부'), '010-3000-3005', SYSDATE - 8, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user06', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600306', '오세훈', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '건축사회환경공학부'), '010-3000-3006', SYSDATE - 7, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user07', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600307', '한지수', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '신소재공학부'), '010-3000-3007', SYSDATE - 6, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user08', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600308', '송민재', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '생명과학부'), '010-3000-3008', SYSDATE - 5, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user09', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600309', '유나경', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '컴퓨터학과'), '010-3000-3009', SYSDATE - 4, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_user10', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600310', '장예린', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '전기전자공학부'), '010-3000-3010', SYSDATE - 3, 'Y' FROM DUAL;


/* =========================================================
   7. 상태 시연용 회원
   ========================================================= */

INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_block01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600113', '정지회원1', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '컴퓨터공학부'), '010-1000-1013', SYSDATE - 20, 'B' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_leave01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600114', '탈퇴회원1', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '산업공학과'), '010-1000-1014', SYSDATE - 25, 'N' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_block01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600213', '정지회원2', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '전기전자공학부'), '010-2000-2013', SYSDATE - 20, 'B' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_leave01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600214', '탈퇴회원2', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '건축공학과'), '010-2000-2014', SYSDATE - 24, 'N' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_block01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600311', '정지회원3', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '전기전자공학부'), '010-3000-3011', SYSDATE - 20, 'B' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_leave01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600312', '탈퇴회원3', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '기계공학부'), '010-3000-3012', SYSDATE - 21, 'N' FROM DUAL;


/* =========================================================
   8. 가입 승인 대기 회원
   - MEMBER만 존재
   - ROLE_USER 미부여
   ========================================================= */

INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_wait01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600118', '승인대기1', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '컴퓨터공학부'), '010-1000-1018', SYSDATE - 2, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'snu_wait02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600119', '승인대기2', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 1 AND DEPT_NAME = '전기정보공학부'), '010-1000-1019', SYSDATE - 1, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_wait01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600218', '승인대기3', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '전기전자공학부'), '010-2000-2018', SYSDATE - 2, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ys_wait02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600219', '승인대기4', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = 2 AND DEPT_NAME = '기계공학부'), '010-2000-2019', SYSDATE - 1, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_wait01', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600313', '승인대기5', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '컴퓨터학과'), '010-3000-3013', SYSDATE - 2, 'Y' FROM DUAL;
INSERT INTO MEMBER SELECT SEQ_MEM.NEXTVAL, 'ku_wait02', '$2a$10$PRAbzoujfcj3a0rnoHgoMOxuHH9vR2qvqO5oAVSBwcCM3nkVn7.j6', '202600314', '승인대기6', (SELECT DEPT_NO FROM DEPARTMENT WHERE UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND DEPT_NAME = '기계공학부'), '010-3000-3014', SYSDATE - 1, 'Y' FROM DUAL;


/* =========================================================
   9. 일반회원 ROLE_USER 부여
   - 일부는 승인대기용으로 제외
   ========================================================= */

-- 서울대
INSERT INTO AUTHORITIES
SELECT 'ROLE_USER', MEM_NO, 1
FROM MEMBER
WHERE MEM_ID IN (
    'snu_user02','snu_user03','snu_user04','snu_user05','snu_user06',
    'snu_user07','snu_user08','snu_user09','snu_user10','snu_user11',
    'snu_user12','snu_user13'
);

-- 연세대
INSERT INTO AUTHORITIES
SELECT 'ROLE_USER', MEM_NO, 2
FROM MEMBER
WHERE MEM_ID IN (
    'ys_user02','ys_user03','ys_user04','ys_user05','ys_user06',
    'ys_user07','ys_user08','ys_user09','ys_user10','ys_user11',
    'ys_user12','ys_user13'
);

-- 고려대
INSERT INTO AUTHORITIES
SELECT 'ROLE_USER',
       MEM_NO,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교')
FROM MEMBER
WHERE MEM_ID IN (
    'ku_user01','ku_user02','ku_user03','ku_user04','ku_user05',
    'ku_user06','ku_user07','ku_user08'
);


/* =========================================================
   10. 공지사항
   ========================================================= */

INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL, 1, '서울대학교 1학기 수강신청 안내', '수강신청 일정 및 유의사항을 확인해주세요.', SYSDATE - 6, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL, 1, '서울대학교 도서관 이용시간 변경', '시험기간 동안 도서관 운영시간이 연장됩니다.', SYSDATE - 4, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL, 2, '연세대학교 중간고사 일정 공지', '과목별 시험 일정을 확인해주세요.', SYSDATE - 5, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL, 2, '연세대학교 학생회 행사 안내', '이번 주 금요일 학생회 주관 행사가 진행됩니다.', SYSDATE - 3, 'Y');

INSERT INTO NOTICE
SELECT SEQ_NOTICE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       '고려대학교 1학기 학사일정 안내',
       '개강, 수강정정, 시험기간 일정을 확인해주세요.',
       SYSDATE - 5,
       'Y'
FROM DUAL;

INSERT INTO NOTICE
SELECT SEQ_NOTICE.NEXTVAL,
       (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교'),
       '고려대학교 공학관 시설 점검 공지',
       '이번 주말 전기설비 점검이 예정되어 있습니다.',
       SYSDATE - 2,
       'Y'
FROM DUAL;


/* =========================================================
   11. 게시글
   ========================================================= */

-- 서울대
INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 1 AND BT.BTYPE_NAME = '자유게시판'),
       '서울대 기숙사 질문 있어요',
       '이번 학기 기숙사 신청해본 분들 꿀팁 좀 알려주세요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'),
       12, SYSDATE - 5, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 1 AND BT.BTYPE_NAME = '질문답변'),
       '전자회로 과제 난이도 어떤가요?',
       '이번 학기 전자회로 들어보신 분들 과제 많은 편인지 궁금합니다.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user02'),
       8, SYSDATE - 4, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 1 AND BT.BTYPE_NAME = '사건사고'),
       '중앙도서관 분실물 보신 분',
       '검은색 필통 분실했습니다. 보신 분은 댓글 부탁드려요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user03'),
       5, SYSDATE - 2, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 1 AND BT.BTYPE_NAME = '전기정보공학부'),
       '전정통 세미나 정보 공유',
       '이번 주 학부 세미나 참석하실 분 있나요?',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user03'),
       21, SYSDATE - 1, 'Y'
FROM DUAL;

-- 연세대
INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 2 AND BT.BTYPE_NAME = '자유게시판'),
       '연세대 학생식당 메뉴 괜찮나요?',
       '오늘 학생식당 메뉴 드셔보신 분 후기 부탁해요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'),
       11, SYSDATE - 5, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 2 AND BT.BTYPE_NAME = '질문답변'),
       '전자회로설계 수업 팀플 있나요?',
       '팀 프로젝트 비중이 큰 편인지 궁금합니다.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user02'),
       9, SYSDATE - 4, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 2 AND BT.BTYPE_NAME = '사건사고'),
       '공학관 앞 자전거 도난 주의',
       '오늘 오전 자전거 도난 사례가 있었다고 합니다. 조심하세요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user03'),
       7, SYSDATE - 3, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = 2 AND BT.BTYPE_NAME = '연세빵'),
       '연세빵 신메뉴 후기',
       '이번에 나온 신메뉴 먹어봤는데 생각보다 괜찮네요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user04'),
       14, SYSDATE - 1, 'Y'
FROM DUAL;

-- 고려대
INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND BT.BTYPE_NAME = '자유게시판'),
       '고려대 열람실 자리 어떤가요?',
       '시험기간에 자리 경쟁 심한 편인지 궁금합니다.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user01'),
       13, SYSDATE - 5, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND BT.BTYPE_NAME = '질문답변'),
       '자료구조 수업 어렵나요?',
       '이번 학기 자료구조 수강 고민 중인데 난이도 궁금합니다.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user02'),
       9, SYSDATE - 4, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND BT.BTYPE_NAME = '사건사고'),
       '공학관 우산 분실하신 분',
       '검정 우산 맡겨뒀습니다. 학생회관 경비실에서 찾아가세요.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user03'),
       6, SYSDATE - 2, 'Y'
FROM DUAL;

INSERT INTO BOARD
SELECT SEQ_BOARD.NEXTVAL,
       (SELECT UBT.UBTYPE_NO FROM UNI_BOARD_TYPE UBT JOIN BOARD_TYPE BT ON UBT.BTYPE_NO = BT.BTYPE_NO WHERE UBT.UNI_NO = (SELECT UNI_NO FROM UNIVERSITY WHERE UNI_NAME = '고려대학교') AND BT.BTYPE_NAME = '고대광장'),
       '고대광장 오늘 행사 정리',
       '학생회 주관 부스 행사 정보 공유합니다.',
       (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user04'),
       17, SYSDATE - 1, 'Y'
FROM DUAL;


/* =========================================================
   12. 댓글
   ========================================================= */

INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '서울대 기숙사 질문 있어요'), '저는 작년에 신청했는데 신청 시작일에 바로 넣는 게 좋아요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user02'), SYSDATE - 4, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전자회로 과제 난이도 어떤가요?'), '과제는 조금 있는 편인데 시험이 더 중요해요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'), SYSDATE - 3, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전정통 세미나 정보 공유'), '저 참석 예정입니다. 발표 주제 괜찮아 보여요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user04'), SYSDATE - 1, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세대 학생식당 메뉴 괜찮나요?'), '오늘 메뉴 무난했어요. 가격도 괜찮았습니다.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user02'), SYSDATE - 4, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전자회로설계 수업 팀플 있나요?'), '팀플 비중 조금 있고 발표도 한 번 있습니다.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'), SYSDATE - 2, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세빵 신메뉴 후기'), '저도 먹어봤는데 생각보다 달지 않아서 좋았어요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user03'), SYSDATE - 1, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고려대 열람실 자리 어떤가요?'), '중간고사 기간에는 아침 일찍 가는 게 좋아요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user02'), SYSDATE - 4, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '자료구조 수업 어렵나요?'), '처음엔 어렵지만 과제 따라가면 괜찮아요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user05'), SYSDATE - 3, 'Y' FROM DUAL;
INSERT INTO REPLY SELECT SEQ_REPLY.NEXTVAL, (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고대광장 오늘 행사 정리'), '정리 감사합니다. 시간표 맞으면 가볼게요.', (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user06'), SYSDATE - 1, 'Y' FROM DUAL;


/* =========================================================
   13. 좋아요
   ========================================================= */

INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '서울대 기숙사 질문 있어요'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user03') FROM DUAL;
INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전자회로 과제 난이도 어떤가요?'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user04') FROM DUAL;
INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세대 학생식당 메뉴 괜찮나요?'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user03') FROM DUAL;
INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세빵 신메뉴 후기'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02') FROM DUAL;
INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고려대 열람실 자리 어떤가요?'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user03') FROM DUAL;
INSERT INTO BOARD_LIKE SELECT (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고대광장 오늘 행사 정리'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user07') FROM DUAL;

INSERT INTO REPLY_LIKE SELECT (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '과제는 조금 있는 편인데 시험이 더 중요해요.'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user03') FROM DUAL;
INSERT INTO REPLY_LIKE SELECT (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '오늘 메뉴 무난했어요. 가격도 괜찮았습니다.'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user04') FROM DUAL;
INSERT INTO REPLY_LIKE SELECT (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '처음엔 어렵지만 과제 따라가면 괜찮아요.'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user08') FROM DUAL;


/* =========================================================
   14. 강의평가
   ========================================================= */

INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '대학수학' AND PROFESSOR_NAME = '김지원'), 4, 4, 5 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user02'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '전자회로' AND PROFESSOR_NAME = '김지원' AND DEPT_NO = 3), 3, 5, 4 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user03'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '아두이노' AND PROFESSOR_NAME = '김지원'), 2, 5, 5 FROM DUAL;

INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '기초화학' AND PROFESSOR_NAME = '한병준'), 4, 3, 4 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user02'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '전자회로' AND PROFESSOR_NAME = '한병준'), 3, 4, 4 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user03'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '건축디자인' AND PROFESSOR_NAME = '한병준'), 5, 4, 5 FROM DUAL;

INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user01'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '자료구조' AND PROFESSOR_NAME = '이교수'), 4, 4, 5 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user02'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '회로이론' AND PROFESSOR_NAME = '정교수'), 3, 4, 4 FROM DUAL;
INSERT INTO LECTURE_ASSESSMENT SELECT SEQ_ASSE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user03'), (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '열역학' AND PROFESSOR_NAME = '한교수'), 4, 3, 4 FROM DUAL;


/* =========================================================
   15. 시간표
   ========================================================= */

INSERT INTO SCHEDULE_TITLE VALUES (SEQ_SCHTITLE.NEXTVAL, '2026-1학기 시간표');
INSERT INTO SCHEDULE_TITLE VALUES (SEQ_SCHTITLE.NEXTVAL, '연세대 1학기 시간표');
INSERT INTO SCHEDULE_TITLE VALUES (SEQ_SCHTITLE.NEXTVAL, '고려대 1학기 시간표');

INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'), 1, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '대학수학' AND PROFESSOR_NAME = '김지원'), 1, 9, 11 FROM DUAL;
INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'), 1, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '전자회로' AND PROFESSOR_NAME = '김지원' AND DEPT_NO = 3), 3, 13, 15 FROM DUAL;

INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'), 2, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '기초화학' AND PROFESSOR_NAME = '한병준'), 2, 10, 12 FROM DUAL;
INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'), 2, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '전자회로설계' AND PROFESSOR_NAME = '한병준'), 4, 14, 16 FROM DUAL;

INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user01'), 3, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '자료구조' AND PROFESSOR_NAME = '이교수'), 1, 10, 12 FROM DUAL;
INSERT INTO SCHEDULE SELECT SEQ_SCHEDULE.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user01'), 3, (SELECT LECTURE_NO FROM LECTURE WHERE LECTURE_NAME = '운영체제' AND PROFESSOR_NAME = '최교수'), 3, 13, 15 FROM DUAL;


/* =========================================================
   16. 출석 / 포인트
   ========================================================= */

INSERT INTO USER_POINT VALUES (3, 120);
INSERT INTO USER_POINT VALUES (4, 95);

-- 서울대
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 7 FROM MEMBER WHERE MEM_ID = 'snu_user02';
INSERT INTO USER_POINT SELECT MEM_NO, 230 FROM MEMBER WHERE MEM_ID = 'snu_user02';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 5 FROM MEMBER WHERE MEM_ID = 'snu_user03';
INSERT INTO USER_POINT SELECT MEM_NO, 180 FROM MEMBER WHERE MEM_ID = 'snu_user03';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 3 FROM MEMBER WHERE MEM_ID = 'snu_user05';
INSERT INTO USER_POINT SELECT MEM_NO, 80 FROM MEMBER WHERE MEM_ID = 'snu_user05';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 6 FROM MEMBER WHERE MEM_ID = 'snu_user06';
INSERT INTO USER_POINT SELECT MEM_NO, 140 FROM MEMBER WHERE MEM_ID = 'snu_user06';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 3, 2 FROM MEMBER WHERE MEM_ID = 'snu_user07';
INSERT INTO USER_POINT SELECT MEM_NO, 60 FROM MEMBER WHERE MEM_ID = 'snu_user07';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 9 FROM MEMBER WHERE MEM_ID = 'snu_user08';
INSERT INTO USER_POINT SELECT MEM_NO, 260 FROM MEMBER WHERE MEM_ID = 'snu_user08';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 4, 5 FROM MEMBER WHERE MEM_ID = 'snu_user09';
INSERT INTO USER_POINT SELECT MEM_NO, 120 FROM MEMBER WHERE MEM_ID = 'snu_user09';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 7 FROM MEMBER WHERE MEM_ID = 'snu_user10';
INSERT INTO USER_POINT SELECT MEM_NO, 200 FROM MEMBER WHERE MEM_ID = 'snu_user10';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 5, 4 FROM MEMBER WHERE MEM_ID = 'snu_user11';
INSERT INTO USER_POINT SELECT MEM_NO, 95 FROM MEMBER WHERE MEM_ID = 'snu_user11';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 8 FROM MEMBER WHERE MEM_ID = 'snu_user12';
INSERT INTO USER_POINT SELECT MEM_NO, 240 FROM MEMBER WHERE MEM_ID = 'snu_user12';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 6 FROM MEMBER WHERE MEM_ID = 'snu_user13';
INSERT INTO USER_POINT SELECT MEM_NO, 170 FROM MEMBER WHERE MEM_ID = 'snu_user13';

-- 연세대
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 6 FROM MEMBER WHERE MEM_ID = 'ys_user02';
INSERT INTO USER_POINT SELECT MEM_NO, 210 FROM MEMBER WHERE MEM_ID = 'ys_user02';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 3, 4 FROM MEMBER WHERE MEM_ID = 'ys_user03';
INSERT INTO USER_POINT SELECT MEM_NO, 160 FROM MEMBER WHERE MEM_ID = 'ys_user03';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 4 FROM MEMBER WHERE MEM_ID = 'ys_user05';
INSERT INTO USER_POINT SELECT MEM_NO, 100 FROM MEMBER WHERE MEM_ID = 'ys_user05';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 6 FROM MEMBER WHERE MEM_ID = 'ys_user06';
INSERT INTO USER_POINT SELECT MEM_NO, 170 FROM MEMBER WHERE MEM_ID = 'ys_user06';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 3, 3 FROM MEMBER WHERE MEM_ID = 'ys_user07';
INSERT INTO USER_POINT SELECT MEM_NO, 75 FROM MEMBER WHERE MEM_ID = 'ys_user07';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 10 FROM MEMBER WHERE MEM_ID = 'ys_user08';
INSERT INTO USER_POINT SELECT MEM_NO, 300 FROM MEMBER WHERE MEM_ID = 'ys_user08';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 4, 5 FROM MEMBER WHERE MEM_ID = 'ys_user09';
INSERT INTO USER_POINT SELECT MEM_NO, 130 FROM MEMBER WHERE MEM_ID = 'ys_user09';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 7 FROM MEMBER WHERE MEM_ID = 'ys_user10';
INSERT INTO USER_POINT SELECT MEM_NO, 210 FROM MEMBER WHERE MEM_ID = 'ys_user10';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 5, 4 FROM MEMBER WHERE MEM_ID = 'ys_user11';
INSERT INTO USER_POINT SELECT MEM_NO, 90 FROM MEMBER WHERE MEM_ID = 'ys_user11';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 8 FROM MEMBER WHERE MEM_ID = 'ys_user12';
INSERT INTO USER_POINT SELECT MEM_NO, 220 FROM MEMBER WHERE MEM_ID = 'ys_user12';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 6 FROM MEMBER WHERE MEM_ID = 'ys_user13';
INSERT INTO USER_POINT SELECT MEM_NO, 160 FROM MEMBER WHERE MEM_ID = 'ys_user13';

-- 고려대
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 6 FROM MEMBER WHERE MEM_ID = 'ku_user01';
INSERT INTO USER_POINT SELECT MEM_NO, 150 FROM MEMBER WHERE MEM_ID = 'ku_user01';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 4 FROM MEMBER WHERE MEM_ID = 'ku_user02';
INSERT INTO USER_POINT SELECT MEM_NO, 90 FROM MEMBER WHERE MEM_ID = 'ku_user02';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 8 FROM MEMBER WHERE MEM_ID = 'ku_user03';
INSERT INTO USER_POINT SELECT MEM_NO, 220 FROM MEMBER WHERE MEM_ID = 'ku_user03';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 3, 5 FROM MEMBER WHERE MEM_ID = 'ku_user04';
INSERT INTO USER_POINT SELECT MEM_NO, 130 FROM MEMBER WHERE MEM_ID = 'ku_user04';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 7 FROM MEMBER WHERE MEM_ID = 'ku_user05';
INSERT INTO USER_POINT SELECT MEM_NO, 200 FROM MEMBER WHERE MEM_ID = 'ku_user05';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 1, 3 FROM MEMBER WHERE MEM_ID = 'ku_user06';
INSERT INTO USER_POINT SELECT MEM_NO, 70 FROM MEMBER WHERE MEM_ID = 'ku_user06';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 4, 6 FROM MEMBER WHERE MEM_ID = 'ku_user07';
INSERT INTO USER_POINT SELECT MEM_NO, 160 FROM MEMBER WHERE MEM_ID = 'ku_user07';
INSERT INTO ATTENDANCE SELECT MEM_NO, SYSDATE - 2, 4 FROM MEMBER WHERE MEM_ID = 'ku_user08';
INSERT INTO USER_POINT SELECT MEM_NO, 100 FROM MEMBER WHERE MEM_ID = 'ku_user08';


/* =========================================================
   17. 신고
   ========================================================= */

-- 기존 신고
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user04'), 5, '도배성 글처럼 보여서 신고합니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '중앙도서관 분실물 보신 분'), SYSDATE - 1 FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user04'), 6, '표현이 다소 공격적으로 느껴졌습니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '팀플 비중 조금 있고 발표도 한 번 있습니다.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user05'), 6, '광고성 글 같습니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고대광장 오늘 행사 정리'), SYSDATE FROM DUAL;

-- 추가 게시글 신고
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user05'), 6, '내용이 반복적이라 보기 불편합니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전자회로 과제 난이도 어떤가요?'), SYSDATE - 1 FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user06'), 5, '같은 주제의 글이 반복 작성된 것 같습니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전정통 세미나 정보 공유'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user05'), 6, '낚시성 제목 같아서 신고합니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세대 학생식당 메뉴 괜찮나요?'), SYSDATE - 1 FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user06'), 5, '반복 게시글처럼 보입니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세빵 신메뉴 후기'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user06'), 6, '내용이 부정확한 것 같아 신고합니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고려대 열람실 자리 어떤가요?'), SYSDATE - 1 FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user07'), 5, '행사 정보글인데 광고처럼 느껴집니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고대광장 오늘 행사 정리'), SYSDATE FROM DUAL;

-- 추가 댓글 신고
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user07'), 1, '댓글 표현이 공격적으로 느껴졌습니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '과제는 조금 있는 편인데 시험이 더 중요해요.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user08'), 6, '도움이 안 되는 댓글 같아요.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '저 참석 예정입니다. 발표 주제 괜찮아 보여요.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user07'), 6, '내용이 부정확해 보여 신고합니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '오늘 메뉴 무난했어요. 가격도 괜찮았습니다.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user08'), 1, '표현이 거슬려서 신고합니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '저도 먹어봤는데 생각보다 달지 않아서 좋았어요.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user08'), 6, '너무 단정적으로 말해서 신고합니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '중간고사 기간에는 아침 일찍 가는 게 좋아요.'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user09'), 5, '반복 댓글처럼 보여 신고합니다.', 'REPLY', (SELECT REPLY_NO FROM REPLY WHERE REPLY_CONTENT = '처음엔 어렵지만 과제 따라가면 괜찮아요.'), SYSDATE FROM DUAL;

-- 동일 대상 추가 신고
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user09'), 5, '유사한 글이 반복되는 것 같습니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '전자회로 과제 난이도 어떤가요?'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user09'), 6, '정보성보다 잡담성 글 같아 보입니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '연세빵 신메뉴 후기'), SYSDATE FROM DUAL;
INSERT INTO REPORT SELECT SEQ_REPORT.NEXTVAL, (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user10'), 5, '홍보성 게시물 같아서 신고합니다.', 'BOARD', (SELECT BOARD_NO FROM BOARD WHERE BOARD_TITLE = '고대광장 오늘 행사 정리'), SYSDATE FROM DUAL;


/* =========================================================
   18. 친구
   ========================================================= */

INSERT INTO FRIENDS SELECT (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user01'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'snu_user02'), 'Y' FROM DUAL;
INSERT INTO FRIENDS SELECT (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'user02'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ys_user02'), 'Y' FROM DUAL;
INSERT INTO FRIENDS SELECT (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user01'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user02'), 'Y' FROM DUAL;
INSERT INTO FRIENDS SELECT (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user03'), (SELECT MEM_NO FROM MEMBER WHERE MEM_ID = 'ku_user04'), 'N' FROM DUAL;


/* =========================================================
   19. 커밋
   ========================================================= */

COMMIT;