/* 테이블 삭제 */
DROP TABLE UNIVERSITY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE AUTHORITIES CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE UNI_BOARD_TYPE CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT_REASON CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE REPLY_LIKE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE USER_POINT CASCADE CONSTRAINTS;
DROP TABLE SEMESTER_LECTURE CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE LECTURE_ASSESSMENT CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE CHAT_JOIN CASCADE CONSTRAINTS;
DROP TABLE FILES CASCADE CONSTRAINTS;
DROP TABLE persistent_logins CONSTRAINTS;

/* 시퀀스 삭제 */
DROP SEQUENCE SEQ_MEM;
DROP SEQUENCE SEQ_UNI;
DROP SEQUENCE SEQ_DEPT;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_BTYPE;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_REASON;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_LECTURE;
DROP SEQUENCE SEQ_ASSE;
DROP SEQUENCE SEQ_SCHTITLE;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_CHAT;
DROP SEQUENCE SEQ_MSG;
DROP SEQUENCE SEQ_FILE;


/* SEQUENCE 생성 */

-- 회원 정보 관련
CREATE SEQUENCE SEQ_UNI NOCACHE;
CREATE SEQUENCE SEQ_DEPT NOCACHE;
CREATE SEQUENCE SEQ_MEM NOCACHE;

-- 공자사항 및 게시판
CREATE SEQUENCE SEQ_NOTICE NOCACHE;
CREATE SEQUENCE SEQ_BOARD NOCACHE;
CREATE SEQUENCE SEQ_BTYPE NOCACHE;
CREATE SEQUENCE SEQ_UBTYPE NOCACHE;
CREATE SEQUENCE SEQ_REPLY NOCACHE;

-- 신고
CREATE SEQUENCE SEQ_REPORT NOCACHE;
CREATE SEQUENCE SEQ_REASON NOCACHE;

-- 강의 및 시간표
CREATE SEQUENCE SEQ_LECTURE NOCACHE;
CREATE SEQUENCE SEQ_ASSE NOCACHE;
CREATE SEQUENCE SEQ_SCHTITLE NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE NOCACHE;

-- 채팅
CREATE SEQUENCE SEQ_CHAT NOCACHE;
CREATE SEQUENCE SEQ_MSG NOCACHE;

-- 첨부파일
CREATE SEQUENCE SEQ_FILE NOCACHE;

--------------------------------------------------------------------------------

/* TABEL 생성 */

-- 회원 정보 관련
CREATE TABLE UNIVERSITY (
    UNI_NO   NUMBER       PRIMARY KEY,
    UNI_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE DEPARTMENT (
    DEPT_NO   NUMBER       PRIMARY KEY,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY NOT NULL,
    DEPT_NAME VARCHAR2(30) NOT NULL,
    UNIQUE(UNI_NO, DEPT_NAME)
);
CREATE TABLE MEMBER (
    MEM_NO      NUMBER        PRIMARY KEY,
    MEM_ID      VARCHAR2(20)  NOT NULL UNIQUE,
    MEM_PW      VARCHAR2(100) NOT NULL,
    STUDENT_NO  NUMBER,
    MEM_NAME    VARCHAR2(20)  NOT NULL,
    DEPT_NO     NUMBER        REFERENCES DEPARTMENT NOT NULL,
    PHONE       VARCHAR2(13),
    CREATE_DATE DATE          DEFAULT SYSDATE,
    STATUS      CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', ,'B' ,'N'))
);
CREATE TABLE AUTHORITIES (
    AUTHORITY VARCHAR2(20),
    MEM_NO    NUMBER       REFERENCES MEMBER,
    UNI_NO    NUMBER       REFERENCES UNIVERSITY,
    PRIMARY KEY(AUTHORITY, MEM_NO, UNI_NO)
);

-- 공지사항 및 게시판
CREATE TABLE NOTICE (
    NOTICE_NO      NUMBER        PRIMARY KEY,
    UNI_NO         NUMBER        REFERENCES UNIVERSITY,
    NOTICE_TITLE   VARCHAR2(50)  NOT NULL,
    NOTICE_CONTENT VARCHAR2(300),
    CREATE_DATE    DATE          DEFAULT SYSDATE,
    STATUS         CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE BOARD_TYPE (
    BTYPE_NO   NUMBER PRIMARY KEY,
    BTYPE_NAME VARCHAR2(20)
);
CREATE TABLE UNI_BOARD_TYPE (
    UBTYPE_NO NUMBER PRIMARY KEY,
    UNI_NO    NUMBER REFERENCES UNIVERSITY,
    BTYPE_NO  NUMBER REFERENCES BOARD_TYPE,
    UNIQUE(UNI_NO, BTYPE_NO)
);
CREATE TABLE BOARD (
    BOARD_NO      NUMBER        PRIMARY KEY,
    UBTYPE_NO     NUMBER        DEFAULT 1 REFERENCES UNI_BOARD_TYPE,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(300),
    BOARD_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    VIEW_COUNT    NUMBER        DEFAULT 0,
    CREATE_DATE   DATE          DEFAULT SYSDATE,
    STATUS        CHAR(1)       DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE BOARD_LIKE(
    BOARD_NO NUMBER REFERENCES BOARD,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(BOARD_NO, MEM_NO)
);
CREATE TABLE REPLY(
    REPLY_NO      NUMBER       PRIMARY KEY,
    BOARD_NO      NUMBER       REFERENCES BOARD NOT NULL,
    REPLY_CONTENT VARCHAR(200) NOT NULL,
    REPLY_WRITER  NUMBER       REFERENCES MEMBER NOT NULL,
    CREATE_DATE   DATE         DEFAULT SYSDATE,
    STATUS        CHAR(1)      DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
CREATE TABLE REPLY_LIKE(
    REPLY_NO NUMBER REFERENCES REPLY,
    MEM_NO   NUMBER REFERENCES MEMBER,
    PRIMARY KEY(REPLY_NO, MEM_NO)
);

-- 신고
CREATE TABLE REPORT_REASON(
    REASON_NO   NUMBER       PRIMARY KEY,
    REASON_NAME VARCHAR2(40)
);
CREATE TABLE REPORT(
    REPORT_NO      NUMBER        PRIMARY KEY,
    REPORT_MEM     NUMBER        REFERENCES MEMBER NOT NULL,
    REASON_NO      NUMBER        DEFAULT 0 REFERENCES REPORT_REASON,
    REASON_CONTENT VARCHAR2(100),
    TARGET_TYPE    VARCHAR2(20)  NOT NULL,
    TARGET_NO      NUMBER        NOT NULL,
    UNIQUE(REPORT_MEM, TARGET_TYPE, TARGET_NO)
);

-- 출석체크 및 포인트
CREATE TABLE ATTENDANCE(
    MEM_NO      NUMBER REFERENCES MEMBER PRIMARY KEY,
    ATTEND_DAYS DATE,
    COUNT       NUMBER DEFAULT 0
);
CREATE TABLE USER_POINT(
    MEM_NO  NUMBER REFERENCES MEMBER PRIMARY KEY,
    POINT   NUMBER DEFAULT 0
);

-- 강의 및 시간표
CREATE TABLE LECTURE(
    LECTURE_NO     NUMBER       PRIMARY KEY,
    DEPT_NO        NUMBER       REFERENCES DEPARTMENT NOT NULL,
    LECTURE_NAME   VARCHAR2(20) NOT NULL,
    PROFESSOR_NAME VARCHAR2(20) NOT NULL,
    UNIQUE(LECTURE_NAME, PROFESSOR_NAME)
);
CREATE TABLE LECTURE_ASSESSMENT(
    ASSE_NO     NUMBER PRIMARY KEY,
    MEM_NO      NUMBER REFERENCES MEMBER NOT NULL,
    LECTURE_NO  NUMBER REFERENCES LECTURE NOT NULL,
    HOMEWORK    NUMBER DEFAULT 1,
    GRADE       NUMBER DEFAULT 1, 
    TOTAL_SOCRE NUMBER DEFAULT 5,
    UNIQUE(MEM_NO, LECTURE_NO)
);
CREATE TABLE SCHEDULE_TITLE(
    SCHTITLE_NO NUMBER PRIMARY KEY,
    SCHTITLE_NAME VARCHAR(30)
);
CREATE TABLE SCHEDULE(
    SCHEDULE_NO  NUMBER PRIMARY KEY,
    MEM_NO       NUMBER REFERENCES MEMBER NOT NULL,
    SCHTITLE_NO  NUMBER REFERENCES SCHEDULE_TITLE DEFAULT 1,
    LECTURE_NO   NUMBER REFERENCES LECTURE NOT NULL,
    SCHEDULE_DAY NUMBER NOT NULL,
    START_TIME   NUMBER NOT NULL,
    END_TIME     NUMBER NOT NULL
);

-- 친구
CREATE TABLE FRIENDS(
    SENDER_NO   NUMBER  REFERENCES MEMBER,
    RECEIVER_NO NUMBER  REFERENCES MEMBER,
    STATUS      CHAR(1) DEFAULT 'N' CHECK (STATUS IN ('Y', 'N')),
    PRIMARY KEY(SENDER_NO, RECEIVER_NO)
);

-- 채팅
CREATE TABLE CHAT(
    CHAT_NO NUMBER PRIMARY KEY,
    CHAT_TITLE VARCHAR2(30) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
CREATE TABLE CHAT_MESSAGE(
    MSG_NO       NUMBER        PRIMARY KEY,
    CHAT_NO      NUMBER        REFERENCES CHAT NOT NULL,
    CHAT_MESSAGE VARCHAR2(100) NOT NULL,
    CHAT_WRITER  NUMBER        REFERENCES MEMBER NOT NULL,
    CREATE_DATE  DATE          DEFAULT SYSDATE
);
CREATE TABLE CHAT_JOIN(
    MEM_NO  NUMBER REFERENCES MEMBER,
    CHAT_NO NUMBER REFERENCES CHAT,
    PRIMARY KEY(MEM_NO, CHAT_NO)
);

-- 첨부파일
CREATE TABLE FILES(
    FILE_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(20),
    CHANGE_NAME VARCHAR2(20),
    TARGET_TYPE VARCHAR2(20) NOT NULL,
    TARGET_NO   NUMBER NOT NULL
);

-- 로그인 유지(remember-me)
CREATE TABLE persistent_logins (
  username        VARCHAR(64)  NOT NULL,
  series          VARCHAR(64)  PRIMARY KEY,
  token           VARCHAR(64)  NOT NULL,
  last_used       TIMESTAMP    NOT NULL
);

--------------------------------------------------------------------------------

/* 테이블 컬럼 삭제 */
DELETE university;
DELETE department;
DELETE member;
DELETE authorities;

SELECT * FROM UNIVERSITY;
SELECT * FROM DEPARTMENT;
SELECT * FROM MEMBER;
SELECT * FROM AUTHORITIES;

--------------------------------------------------------------------------------

/* 대학 정보 추가 */
INSERT INTO UNIVERSITY VALUES(0, 'MASTER');
INSERT INTO UNIVERSITY VALUES(SEQ_UNI.NEXTVAL, '서울대학교');
INSERT INTO UNIVERSITY VALUES(SEQ_UNI.NEXTVAL, '연세대학교');

/* 학과 정보 추가 */
INSERT INTO DEPARTMENT VALUES(0, 0, 'MASTER');

-- 서울대 학과 정보
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '공통교양');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건설환경도시공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건설환경도시공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '기계공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '재료공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '전기정보공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '컴퓨터공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '화학생물공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '건축학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '산업공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '에너지자원공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '원자핵공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '조선해양공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 1, '항공우주공학과');

-- 연대 학과 정보
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '공통교양');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '화공생명공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '전기전자공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '기계공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '사회환경시스템공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '건축공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '신소재공학부');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '도시공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '산업공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '시스템반도체공학과');
INSERT INTO DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL, 2, '디스플레이융합공학과');

/* 회원 추가 */

-- 마스터 계정 : master / master00
INSERT INTO MEMBER VALUES(0, 'master', 
    '$2a$10$8HDkwdh12AAm36syCfqoVOvyxkJY6kMZSySGlV5t/Bk8htbk7V52q', 
    NULL, 'master', 0, NULL, DEFAULT, DEFAULT);
-- 서울대 관리자 : seoul / seoul000
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'seoul', 
    '$2a$10$8L4WDdUeAu4QdMOp.sB12OlsGUiMgY6aIvyRA6uoY23p8E4Bph7km', 
    NULL, 'seoul', 1, NULL, DEFAULT, DEFAULT);
-- 연대 관리자 : yonsei / yonsei00
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'yonsei', 
    '$2a$10$mL2Q5qNo.36wnvKv8AYtD.mxRnSqACWEemDwagjFn20Tcb0SmGNt6', 
    NULL, 'yonsei', 15, NULL, DEFAULT, DEFAULT);


/* 권한 정보 추가 */
INSERT INTO AUTHORITIES VALUES('ROLE_USER', 0, 0);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 0, 0);
INSERT INTO AUTHORITIES VALUES('ROLE_MASTER', 0, 0);

INSERT INTO AUTHORITIES VALUES('ROLE_USER', 1, 1);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 1, 1);

INSERT INTO AUTHORITIES VALUES('ROLE_USER', 2, 2);
INSERT INTO AUTHORITIES VALUES('ROLE_ADMIN', 2, 2);

/* 게시판 카테고리 정보 추가 */
INSERT INTO BOARD_TYPE VALUES(SEQ_BTYPE, '자유게시판');
INSERT INTO BOARD_TYPE VALUES(SEQ_BTYPE, '질문답변');
INSERT INTO BOARD_TYPE VALUES(SEQ_BTYPE, '사건사고');
INSERT INTO BOARD_TYPE VALUES(SEQ_BTYPE, '전기정보공학부');
INSERT INTO BOARD_TYPE VALUES(SEQ_BTYPE, '연세빵');

INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 1, 1);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 1, 2);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 1, 3);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 1, 4);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 2, 1);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 2, 2);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 2, 3);
INSERT INTO UNI_BOARD_TYPE VALUES(SEQ_UBTYPE, 2, 5);

/* 강의 정보 추가 */
INSERT INTO LECTURE VALUES(SEQ_LECTURE, 1, '대학수학', '김지원');
INSERT INTO LECTURE VALUES(SEQ_LECTURE, 15, '자기소개서', '한병준');

commit;